# default configuration
# ---------------------
spring:
  application:
    name: AmqToOaq
  jta:
    enabled: true
    transaction-manager-id: myJtaTrxMgr
    atomikos:
      properties:
        service: com.atomikos.icatch.standalone.UserTransactionServiceFactory
        max-actives: 200
        transaction-manager-unique-name: Unique Transaction Manager Name
        default-jta-timeout: 300000

activemq:
  brokerUrl: tcp://localhost:61616

oracle:
  url: jdbc:oracle:thin:@localhost:1525:xe
  username: aq
  password: aq
